apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pod.label }}
spec:
  selector:
    app: {{ .Values.pod.label }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
