name: Build and Deploy to AWS EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/test:latest
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Deploy to AWS EKS with Helm
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig

          helm upgrade --install test ./helm \
            --namespace dev \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/test \
            --set image.tag=latest
