on:
  push:
    branches: [main]
  workflow_dispatch:
env:
  EKS_CLUSTER_NAME: ${{secrets.CLUSTER_NAME}}
  AWS_REGION: ${{secrets.AWS_DEPLOYMENT_REGION}}
  USER: ${{secrets.DOCKERHUB_USERNAME}}
  REPO: test
  RELEASE_NAME: test
  NAMESPACE: dev

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Set short git commit SHA
        id: commit
        uses: prompt/actions-commit-hash@v2
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag ${{env.USER}}/${{env.REPO}}:${{ steps.commit.outputs.short }}

      - name: Push Docker image
        run: docker push ${{env.USER}}/${{env.REPO}}:${{ steps.commit.outputs.short }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Update Image tag
        env:
          IMAGE_TAG: ${{ steps.commit.outputs.short }}
        run: |
          sed -i.bak "s|tag:.*|tag: $IMAGE_TAG|g" helm/values.yaml

      - name: Deploy helm chart
        uses: llm-team-org/aws-eks-helm-docker@helm-test
        with:
          exec: helm upgrade --install ${{env.RELEASE_NAME}}  helm/ -n ${{env.NAMESPACE}}
